export const FETCH_SITES = "FETCH_SITES";
export const TOGGLE_SITE = "TOGGLE_SITE";
export const DESELECT_SITE = "DESELECT_SITE";
export const SELECT_ALL_SITES = "SELECT_ALL_SITES";
export const RESET_SELECTED_SITES = "RESET_SELECTED_SITES";
